# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  tagDate: $[ format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}.{0:mm}{0:ss}', pipeline.startTime) ]
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  
stages:
- stage: Build
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image and Push
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/geoserver_2_25/Dockerfile'
        tags: | 
              latest
              $(tagDate)_ver2.25
        containerRegistry: DockerHub
        repository: dbcawa/appsteam-geoserver
      env:
        DOCKER_BUILDKIT: 1
        repository: dbcawa/docker_app_dev       
