#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:             postgresql
# Required-Start:       $local_fs $remote_fs $network $time
# Required-Stop:        $local_fs $remote_fs $network $time
# Should-Start:         $syslog
# Should-Stop:          $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    PostgreSQL RDBMS server
### END INIT INFO

case "$1" in
    start|stop|restart|reload)
        if [ "$1" = "start" ]; then
            chown -R 999:999 /var/lib/postgresql/data/
        fi
        exit ${EXIT:-0}
        ;;
    status)
        LS=`ls -al /var/lib/postgresql/data`
        echo "Not applicable to this process"
        ;;
    force-reload)
        echo "Not applicable to this process"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload|force-reload|status} [version ..]"
        exit 1
        ;;
esac

exit 0
